# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install newgrounds
          haxelib install polymod
          haxelib git polymod https://github.com/larsiusprime/polymod funkinfixes
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib git djFlixel https://github.com/john32b/djFlixel
          haxelib install actuate
          haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
          haxelib git systools https://github.com/haya3218/systools
          haxelib list
        shell: cmd
      - name: Rebuild extension-webm
        run: haxelib run lime rebuild extension-webm windows
      - name: Rebuild systools
        run: haxelib run lime rebuild systools windows
      - name: Compile
        run: haxelib run lime build windows -debug
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Build
          path: export/release/windows/bin
